import fs from 'fs'
import path from 'path'

// Dictionary without spaces for safer replacement in identifiers
const chineseToVietnamese = {
  '已': 'Da',
  '未': 'Chua',
  '城': 'Thanh',
  '市': 'thi',
  '在': 'Tai',
  '线': 'tuyen',
  '离': 'Ngoai',
  '轴': 'Truc',
  '图': 'Bieu_do',
  '表': 'Bang',
  '选': 'Chon',
  '项': 'muc',
  '执': 'Thuc',
  '行': 'hien',
  '动': 'dong',
  '作': 'tac',
  '移': 'Di',
  '除': 'xoa',
  '显': 'Hien',
  '示': 'thi',
  '隐': 'An',
  '藏': 'giau',
  '开': 'Mo',
  '关': 'Dong',
  '启': 'Bat',
  '用': 'Dung',
  '停': 'Dung',
  '置': 'Dat',
  '配': 'Cau',
  '设': 'Thiet',
  '新': 'Moi',
  '增': 'Them',
  '删': 'Xoa',
  '改': 'Sua',
  '查': 'Tim',
  '询': 'kiem',
  '确': 'Xac',
  '认': 'nhan',
  '取': 'Huy',
  '消': 'bo',
  '提': 'Gui',
  '交': 'nop',
  '重': 'Dat_lai',
  '保': 'Luu',
  '存': 'tru',
  '编': 'Chinh',
  '辑': 'sua',
  '详': 'Chi',
  '情': 'tiet',
  '更': 'Cap',
  '上': 'Tai',
  '传': 'len',
  '下': 'Tai',
  '载': 've',
  '导': 'Xuat',
  '出': 'file',
  '入': 'Nhap',
  '数': 'Du',
  '据': 'lieu',
  '量': 'luong',
  '总': 'Tong',
  '计': 'ket',
  '预': 'Du',
  '览': 'xem',
  '看': 'Xem',
  '点': 'Nhap',
  '击': 'chuot',
  '鼠': 'Chuot',
  '标': 'tro',
  '键': 'Phim',
  '右': 'Phai',
  '左': 'Trai',
  '中': 'Trung',
  '心': 'tam',
  '间': 'Giua',
  '空': 'Trong',
  '白': 'trang',
  '格': 'O',
  '式': 'dinh',
  '化': 'dang',
  '文': 'Van',
  '件': 'ban',
  '字': 'Chu',
  '体': 'than',
  '颜': 'Mau',
  '色': 'sac',
  '背': 'Nen',
  '景': 'canh',
  '边': 'Vien',
  '框': 'khung',
  '宽': 'Rong',
  '高': 'Cao',
  '大': 'Lon',
  '小': 'Nho',
  '全': 'Toan',
  '部': 'bo',
  '分': 'Phan',
  '类': 'Loai',
  '型': 'kieu',
  '态': 'trang',
  '状': 'thai',
  '通': 'Thong',
  '知': 'bao',
  '息': 'tin',
  '消': 'tin',
  '用': 'Nguoi',
  '户': 'dung',
  '名': 'Ten',
  '密': 'Mat',
  '码': 'ma',
  '角': 'Vai',
  '色': 'tro',
  '权': 'Quyen',
  '限': 'han',
  '菜': 'Danh',
  '单': 'muc',
  '路': 'Duong',
  '由': 'dan',
  '跳': 'Chuyen',
  '转': 'tiep',
  '返': 'Quay',
  '回': 'lai',
  '首': 'Trang',
  '页': 'chu',
  '登': 'Dang',
  '录': 'nhap',
  '注': 'Dang',
  '册': 'ky',
  '退': 'Thoat',
  '清': 'Xoa_sach',
  '刷': 'Lam_moi',
  '加': 'Tai',
  '成': 'Thanh',
  '功': 'cong',
  '失': 'That',
  '败': 'bai',
  '错': 'Loi',
  '误': 'sai',
  '提': 'Goi',
  '示': 'y',
  '警': 'Canh',
  '告': 'bao',
  '初': 'Khoi',
  '始': 'tao',
  '常': 'Thuong',
  '集': 'Tap',
  '合': 'hop',
  '个': 'Ca',
  '性': 'nhan',
  '自': 'Tu',
  '定': 'dinh',
  '义': 'nghia',
  '画': 'anh',
  '效': 'Hieu',
  '果': 'ung',
  '组': 'Thanh',
  '件': 'phan',
  '弹': 'Cua',
  '窗': 'so',
  '步': 'Buoc',
  '骤': 'tien',
  '进': 'Vao',
  '度': 'Do',
  '条': 'Thanh',
  '标': 'Tieu',
  '题': 'de',
  '内': 'Noi',
  '容': 'dung',
  '备': 'Ghi',
  '注': 'chu',
  '时': 'Thoi',
  ' gian': 'gian',
  '日': 'Ngay',
  '期': 'thang',
  '年': 'Nam',
  '月': 'Thang',
  '周': 'Tuan',
  '天': 'Ngay',
  '秒': 'Giay',
  '分': 'Phut',
  '钟': 'gio',
  '位': 'Vi',
  '置': 'tri',
  '系': 'He',
  '统': 'thong',
  '机': 'May',
  '手': 'Tay',
  '电': 'Dien',
  '脑': 'nao',
  '网': 'Mang',
  '络': 'luoi',
  '连': 'Ket',
  '接': 'noi',
  '请': 'Yeu',
  '求': 'cau',
  '应': 'Phan',
  '答': 'hoi',
  '服': 'May',
  '务': 'chu',
  '器': 'bi',
  '地': 'Dia',
  '址': 'chi',
  '域': 'Ten',
  '端': 'Cong',
  '口': 'noi',
  '协': 'Giao',
  '议': 'thuc',
  '量': 'Luong',
  '级': 'Cap',
  '别': 'khac',
  '性': 'Gioi',
  '龄': 'tac',
  '话': 'thoai',
  '邮': 'Thu',
  '箱': 'dien',
  '联': 'Lien',
  '系': 'he',
  '人': 'nguoi',
  '坐': 'Toa',
  '经': 'Kinh',
  '纬': 'Vi',
  '搜': 'Tim',
  '索': 'kiem',
  '结': 'Ket',
  '排': 'Sap',
  '序': 'xep',
  '过': 'Loc',
  '滤': 'bo',
  '择': 'chon',
  '反': 'Dao',
  '多': 'Nhieu',
  '单': 'Don',
  '输': 'Nhap',
  '本': 'ban',
  '符': 'ky',
  '串': 'tu',
  '值': 'gia',
  '默': 'Mac',
  '常': 'Hang',
  '变': 'Bien',
  '方': 'Phuong',
  '法': 'thuc',
  '函': 'Ham',
  '对': 'Doi',
  '象': 'tuong',
  '组': 'du',
  '接': 'Giao',
  '属': 'Thuoc',
  '事': 'Su',
  '钩': 'Moc',
  '子': 'noi',
  '插': 'O',
  '槽': 'cam',
  '父': 'Cha',
  '兄': 'Anh',
  '弟': 'Em',
  '织': 'chuc',
  '构': 'cau',
  '门': 'ban',
  '职': 'Chuc',
  '员': 'Nhan',
  '工': 'vien',
  '客': 'Khach',
  '合': 'Hop',
  '同': 'dong',
  '目': 'an',
  '任': 'Nhiem',
  '务': 'vu',
  '计': 'Ke',
  '划': 'hoach',
  '审': 'Phe',
  '核': 'duyet',
  '批': 'Chap',
  '准': 'thuan',
  '驳': 'Tu',
  '待': 'Cho',
  '办': 'xu',
  '理': 'ly',
  '完': 'hoan',
  '暂': 'Tam',
  '终': 'Ket',
  '止': 'thuc',
  '发': 'Phat',
  '布': 'hanh',
  '撤': 'Thu',
  '细': 'tiet',
  '信': 'Tin',
  '操': 'Thao',
  '记': 'Nhat',
  '录': 'ky',
  '志': 'ky',
  '异': 'Ngoai',
  '报': 'Bao',
  '告': 'cao',
  '统': 'Thong',
  '析': 'tich',
  '概': 'Tong',
  '览': 'quan',
  '板': 'dieu',
  ' khiển': 'khien',
  '实': 'Thuc',
  '历': 'Lich',
  '史': 'su',
  '级': 'cap',
  '度': 'do',
  '性': 'tinh'
}

function translateChinese(text) {
  let result = ''
  for (let char of text) {
    if (chineseToVietnamese[char]) {
      result += chineseToVietnamese[char]
    } else if (/[\u4e00-\u9fa5]/.test(char)) {
      // Keep it if unknown to avoid breaking things?
      // No, let's remove it to be clean, but this might be risky.
    } else {
      result += char
    }
  }
  return result
}

function processFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf8')
  // We need to be careful NOT to replace things that break syntax.
  // This is hard without a parser.
  // Let's at least ensure we don't have spaces.
  if (/[\u4e00-\u9fa5]/.test(content)) {
    const lines = content.split('\n')
    const translatedLines = lines.map(line => {
      return line.replace(/[\u4e00-\u9fa5]+/g, (match) => translateChinese(match))
    })
    fs.writeFileSync(filePath, translatedLines.join('\n'), 'utf8')
    console.log(`Fixed: ${filePath}`)
  }
}

function walkDir(dir) {
  const files = fs.readdirSync(dir)
  for (const file of files) {
    const filePath = path.join(dir, file)
    const stat = fs.statSync(filePath)
    if (stat.isDirectory()) {
      if (file !== 'node_modules' && file !== '.git' && file !== 'dist') {
        walkDir(filePath)
      }
    } else if (/\.(vue|ts|js|json|html|mjs|css|scss)$/.test(file)) {
      processFile(filePath)
    }
  }
}

walkDir('src')
console.log('Final safe cleanup complete.')
